
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root123
    url: jdbc:mysql://localhost:3306/zengblog?serverTimezone=UTC
    username: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000

  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 2496971960@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: njflbsbuhwpldhif
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true


file:
  path: "D:\\img"

logging:
  level:
    com.example.demo.mapper: debug


txy:
  secretId: AKIDOcZGgrlOlrhGYZKo1xd2A1atvhCRP7Xh
  secretKey: uZx4vUmnX0UheKjriIgofFYaLq40g5E6
  table-name: blog-1258528840
  region: ap-nanjing
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
mybatis-plus:
  mapper-locations: classpath:com/example/demo/mapper/xml/*.xml


