
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root123
    url: jdbc:mysql://localhost:3306/zengblog?serverTimezone=UTC
    username: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


file:
  path: "D:\\img"

logging:
  level:
    com.example.demo.mapper: debug


txy:
  secretId: AKIDOcZGgrlOlrhGYZKo1xd2A1atvhCRP7Xh
  secretKey: uZx4vUmnX0UheKjriIgofFYaLq40g5E6
  table-name: blog-1258528840
  region: ap-nanjing
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
mybatis-plus:
  mapper-locations: classpath:com/example/demo/mapper/xml/*.xml
